# Generated by Django 2.1.7 on 2019-03-23 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=60)),
                ('zipcode', models.CharField(max_length=5)),
                ('cuisine', models.CharField(max_length=100)),
                ('restaurant_id', models.CharField(blank=True, max_length=10)),
                ('url', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('user_rating', models.FloatField(blank=True, default=None, null=True)),
                ('num_votes', models.IntegerField(null=True)),
                ('average_cost_for_two', models.IntegerField(null=True)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
            ],
        ),
    ]
